// <auto-generated />
using System;
using CRM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220513204502_agentesprospectos")]
    partial class agentesprospectos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Entidades.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("CRM.Entidades.AgenteProspecto", b =>
                {
                    b.Property<int>("AgenteId")
                        .HasColumnType("int");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("AgenteId", "ProspectoId");

                    b.HasIndex("ProspectoId");

                    b.ToTable("AgentesProspectos");
                });

            modelBuilder.Entity("CRM.Entidades.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProspectoId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CRM.Entidades.Prospecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UrlPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prospectos");
                });

            modelBuilder.Entity("CRM.Entidades.AgenteProspecto", b =>
                {
                    b.HasOne("CRM.Entidades.Agente", "Agente")
                        .WithMany("AgentesProspectos")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Entidades.Prospecto", "Prospecto")
                        .WithMany("AgentesProspectos")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Prospecto");
                });

            modelBuilder.Entity("CRM.Entidades.Contacto", b =>
                {
                    b.HasOne("CRM.Entidades.Prospecto", "Prospecto")
                        .WithMany("Contactos")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospecto");
                });

            modelBuilder.Entity("CRM.Entidades.Agente", b =>
                {
                    b.Navigation("AgentesProspectos");
                });

            modelBuilder.Entity("CRM.Entidades.Prospecto", b =>
                {
                    b.Navigation("AgentesProspectos");

                    b.Navigation("Contactos");
                });
#pragma warning restore 612, 618
        }
    }
}
